version: "3"
services:
  mysql-standalone:
    image: "mysql:5.6"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employeemanager
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
  demo:
    image: "demo"
    ports:
      - "8080:8080"
    depends_on:
      - mysql-standalone
